### PR TITLE
Added two missing functionalities: always & hanging getValue

### PR DESCRIPTION
**Pull request by iain17**
Hi there,

Thank you for this simple promise library. I've taken the liberty to add two calls I was missing during usage of this library. I've tried to make minimal changes:

- getValue allows the user to get a value of the promise. This is helpful in use cases where you'd like to wait until a promise is either rejected or resolved and get the value.
- always allows the user to set a callback for when the promise is either rejected or resolved.

I hope this helps. Let me know if there are any changes I should make.

### CODE REVIEW

**Comment by hilljh82** [comment]
@iain17 Thank you for your interest in this library, and your contributions. Although I am interested in the additions, I have several concerns with this PR.

1. There are two features in this single PR. I would recommend submitting a separate PR for each feature. This way, I can review and address concerns related to each feature in its own PR.

2. Given what you have added, it diff shows you make a LOT of changes to source lines that have nothing to do with the feature in either PR. Please fix this so that the PR only includes changes related to the lines related to the feature.

3. The `getValue()` method you added could be of some use, but I think that its location is misplaced. It should not be placed on the `Promise` class since it goes against the intent of the `Promise` class. Moreover, it will make the `Promise` behave more like a `Future`, and users will eventually misuse this part of the library. As we know from good software design, classes should not have multiple responsibilities (i.e., the S from the SOLID principles of software design). A better solution would be to create a utility class that accepts a Promise in the constructor. You can then place the "busy" wait on the utility class.

4. The current implementation of `getValue()` has a magic number. This is a code smell, and need to be removed. Likewise, you are making the assumption that everyone will want to check at the desired value you provide. Unfortunately, this is not a good design and makes the method less portable (i.e., a sign of rotten design). You would be better off create a default constant for the default sleep time, and overloading the `getValue()` method with one that takes a timeout parameter, and one that does not. The one that does not invokes the one that takes a parameter using the default value.

5. Another major concern with `getValue()` is there is no way to cancel it. For example, what if a promise takes too long to return? The `getValue()` will continue waiting, and the client will have no way to cancel the wait. This could be addressed if you had a utility class that performed the wait instead of placing this method on the promise. This utility class would be a wrapper facade, which could expose methods for managing the wait.

6. The always() method is good and something I have been meaning to add. I just have not had time to add it. I, however, prefer that we name it `finally` or `_finally`.

7. Did you add support for Android? If not, then this needs to be added as well.

8. Did you add test cases to make sure the code you added works and continues to work as this library is evolved.

Again, thank you for your contribution.

**Comment by iain17** [comment]
@hilljh82 Thanks for your reply. I understand your feedback completely and will make the necessary changes.

**Comment by hilljh82** [comment]
@iain17 Great!

BTW, I could not tell, but please make sure you are developing against the latest version in master. I made a LOT of changes to the internals to improve performance on Android.

**Comment by iain17** [comment]
That sounds great. I'll make sure I do when I find more time to work on this. Thank you.

**Comment by hilljh82** [comment]
@iain17 I wanted to let you know that I implemented the `await` function from JavaScript. This is similar to the `getValue` method you proposed. You use the `await` function as follows:

```java
import static com.onehilltech.promises.Promise.await;

// ...
try
{
  let result = await (Promise.resolve (5)); 
}
catch (Exception reason)
{

}
```

Basically, the `await` method takes a `Promise` as a parameter. The caller will block until the promise is settled. If the promise is resolved, then it returns the resolved value. If the promise is rejected, then it throws the reason for rejection.

**Pull request closed without merging**
